//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationWeb.Client.RegistrationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationServiceReference.IRegistrationDataService")]
    public interface IRegistrationDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetStudents", ReplyAction="http://tempuri.org/IRegistrationDataService/GetStudentsResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetStudents", ReplyAction="http://tempuri.org/IRegistrationDataService/GetStudentsResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetStudentsUsers", ReplyAction="http://tempuri.org/IRegistrationDataService/GetStudentsUsersResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.StudentUserDAO[] GetStudentsUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetStudentsUsers", ReplyAction="http://tempuri.org/IRegistrationDataService/GetStudentsUsersResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.StudentUserDAO[]> GetStudentsUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetRegistrarUsers", ReplyAction="http://tempuri.org/IRegistrationDataService/GetRegistrarUsersResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.RegistrarUserDAO[] GetRegistrarUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetRegistrarUsers", ReplyAction="http://tempuri.org/IRegistrationDataService/GetRegistrarUsersResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.RegistrarUserDAO[]> GetRegistrarUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetCourses", ReplyAction="http://tempuri.org/IRegistrationDataService/GetCoursesResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO[] GetCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetCourses", ReplyAction="http://tempuri.org/IRegistrationDataService/GetCoursesResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO[]> GetCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetSessions", ReplyAction="http://tempuri.org/IRegistrationDataService/GetSessionsResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[] GetSessions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetSessions", ReplyAction="http://tempuri.org/IRegistrationDataService/GetSessionsResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[]> GetSessionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/RegisterStudent", ReplyAction="http://tempuri.org/IRegistrationDataService/RegisterStudentResponse")]
        bool RegisterStudent(int studentId, int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/RegisterStudent", ReplyAction="http://tempuri.org/IRegistrationDataService/RegisterStudentResponse")]
        System.Threading.Tasks.Task<bool> RegisterStudentAsync(int studentId, int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/DropFromSession", ReplyAction="http://tempuri.org/IRegistrationDataService/DropFromSessionResponse")]
        bool DropFromSession(int studentId, int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/DropFromSession", ReplyAction="http://tempuri.org/IRegistrationDataService/DropFromSessionResponse")]
        System.Threading.Tasks.Task<bool> DropFromSessionAsync(int studentId, int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/AddCourseBookmark", ReplyAction="http://tempuri.org/IRegistrationDataService/AddCourseBookmarkResponse")]
        bool AddCourseBookmark(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/AddCourseBookmark", ReplyAction="http://tempuri.org/IRegistrationDataService/AddCourseBookmarkResponse")]
        System.Threading.Tasks.Task<bool> AddCourseBookmarkAsync(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/RemoveCourseBookmark", ReplyAction="http://tempuri.org/IRegistrationDataService/RemoveCourseBookmarkResponse")]
        bool RemoveCourseBookmark(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToRemove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/RemoveCourseBookmark", ReplyAction="http://tempuri.org/IRegistrationDataService/RemoveCourseBookmarkResponse")]
        System.Threading.Tasks.Task<bool> RemoveCourseBookmarkAsync(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToRemove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetBookmarks", ReplyAction="http://tempuri.org/IRegistrationDataService/GetBookmarksResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO[] GetBookmarks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetBookmarks", ReplyAction="http://tempuri.org/IRegistrationDataService/GetBookmarksResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO[]> GetBookmarksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetSchedules", ReplyAction="http://tempuri.org/IRegistrationDataService/GetSchedulesResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.ScheduleDAO[] GetSchedules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetSchedules", ReplyAction="http://tempuri.org/IRegistrationDataService/GetSchedulesResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.ScheduleDAO[]> GetSchedulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/InsertCourse", ReplyAction="http://tempuri.org/IRegistrationDataService/InsertCourseResponse")]
        bool InsertCourse(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/InsertCourse", ReplyAction="http://tempuri.org/IRegistrationDataService/InsertCourseResponse")]
        System.Threading.Tasks.Task<bool> InsertCourseAsync(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/CancelCourse", ReplyAction="http://tempuri.org/IRegistrationDataService/CancelCourseResponse")]
        bool CancelCourse(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/CancelCourse", ReplyAction="http://tempuri.org/IRegistrationDataService/CancelCourseResponse")]
        System.Threading.Tasks.Task<bool> CancelCourseAsync(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/InsertStudent", ReplyAction="http://tempuri.org/IRegistrationDataService/InsertStudentResponse")]
        bool InsertStudent(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/InsertStudent", ReplyAction="http://tempuri.org/IRegistrationDataService/InsertStudentResponse")]
        System.Threading.Tasks.Task<bool> InsertStudentAsync(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/RemoveStudent", ReplyAction="http://tempuri.org/IRegistrationDataService/RemoveStudentResponse")]
        bool RemoveStudent(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/RemoveStudent", ReplyAction="http://tempuri.org/IRegistrationDataService/RemoveStudentResponse")]
        System.Threading.Tasks.Task<bool> RemoveStudentAsync(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetStudentSchedule", ReplyAction="http://tempuri.org/IRegistrationDataService/GetStudentScheduleResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[] GetStudentSchedule(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/GetStudentSchedule", ReplyAction="http://tempuri.org/IRegistrationDataService/GetStudentScheduleResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[]> GetStudentScheduleAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/ListEnrolledStudents", ReplyAction="http://tempuri.org/IRegistrationDataService/ListEnrolledStudentsResponse")]
        RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[] ListEnrolledStudents(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationDataService/ListEnrolledStudents", ReplyAction="http://tempuri.org/IRegistrationDataService/ListEnrolledStudentsResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[]> ListEnrolledStudentsAsync(int sessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationDataServiceChannel : RegistrationWeb.Client.RegistrationServiceReference.IRegistrationDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationDataServiceClient : System.ServiceModel.ClientBase<RegistrationWeb.Client.RegistrationServiceReference.IRegistrationDataService>, RegistrationWeb.Client.RegistrationServiceReference.IRegistrationDataService {
        
        public RegistrationDataServiceClient() {
        }
        
        public RegistrationDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.StudentUserDAO[] GetStudentsUsers() {
            return base.Channel.GetStudentsUsers();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.StudentUserDAO[]> GetStudentsUsersAsync() {
            return base.Channel.GetStudentsUsersAsync();
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.RegistrarUserDAO[] GetRegistrarUsers() {
            return base.Channel.GetRegistrarUsers();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.RegistrarUserDAO[]> GetRegistrarUsersAsync() {
            return base.Channel.GetRegistrarUsersAsync();
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO[] GetCourses() {
            return base.Channel.GetCourses();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO[]> GetCoursesAsync() {
            return base.Channel.GetCoursesAsync();
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[] GetSessions() {
            return base.Channel.GetSessions();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[]> GetSessionsAsync() {
            return base.Channel.GetSessionsAsync();
        }
        
        public bool RegisterStudent(int studentId, int sessionId) {
            return base.Channel.RegisterStudent(studentId, sessionId);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterStudentAsync(int studentId, int sessionId) {
            return base.Channel.RegisterStudentAsync(studentId, sessionId);
        }
        
        public bool DropFromSession(int studentId, int sessionId) {
            return base.Channel.DropFromSession(studentId, sessionId);
        }
        
        public System.Threading.Tasks.Task<bool> DropFromSessionAsync(int studentId, int sessionId) {
            return base.Channel.DropFromSessionAsync(studentId, sessionId);
        }
        
        public bool AddCourseBookmark(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToAdd) {
            return base.Channel.AddCourseBookmark(bookmarkToAdd);
        }
        
        public System.Threading.Tasks.Task<bool> AddCourseBookmarkAsync(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToAdd) {
            return base.Channel.AddCourseBookmarkAsync(bookmarkToAdd);
        }
        
        public bool RemoveCourseBookmark(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToRemove) {
            return base.Channel.RemoveCourseBookmark(bookmarkToRemove);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveCourseBookmarkAsync(RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO bookmarkToRemove) {
            return base.Channel.RemoveCourseBookmarkAsync(bookmarkToRemove);
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO[] GetBookmarks() {
            return base.Channel.GetBookmarks();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.BookmarkedSessionDAO[]> GetBookmarksAsync() {
            return base.Channel.GetBookmarksAsync();
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.ScheduleDAO[] GetSchedules() {
            return base.Channel.GetSchedules();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.ScheduleDAO[]> GetSchedulesAsync() {
            return base.Channel.GetSchedulesAsync();
        }
        
        public bool InsertCourse(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course) {
            return base.Channel.InsertCourse(course);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCourseAsync(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course) {
            return base.Channel.InsertCourseAsync(course);
        }
        
        public bool CancelCourse(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course) {
            return base.Channel.CancelCourse(course);
        }
        
        public System.Threading.Tasks.Task<bool> CancelCourseAsync(RegistrationWeb.Logic.RegistrationServiceReference.CourseDAO course) {
            return base.Channel.CancelCourseAsync(course);
        }
        
        public bool InsertStudent(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student) {
            return base.Channel.InsertStudent(student);
        }
        
        public System.Threading.Tasks.Task<bool> InsertStudentAsync(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student) {
            return base.Channel.InsertStudentAsync(student);
        }
        
        public bool RemoveStudent(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student) {
            return base.Channel.RemoveStudent(student);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveStudentAsync(RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO student) {
            return base.Channel.RemoveStudentAsync(student);
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[] GetStudentSchedule(int studentId) {
            return base.Channel.GetStudentSchedule(studentId);
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.CourseSessionDAO[]> GetStudentScheduleAsync(int studentId) {
            return base.Channel.GetStudentScheduleAsync(studentId);
        }
        
        public RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[] ListEnrolledStudents(int sessionId) {
            return base.Channel.ListEnrolledStudents(sessionId);
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Logic.RegistrationServiceReference.StudentDAO[]> ListEnrolledStudentsAsync(int sessionId) {
            return base.Channel.ListEnrolledStudentsAsync(sessionId);
        }
    }
}
