//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookmarkedSession
    {
        public int Id { get; set; }
        public int StudentUserId { get; set; }
        public int SessionId { get; set; }
    
        public virtual CourseSession CourseSession { get; set; }
        public virtual StudentUser StudentUser { get; set; }
    }
}
