//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentUser()
        {
            this.BookmarkedSessions = new HashSet<BookmarkedSession>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
        public int StudentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookmarkedSession> BookmarkedSessions { get; set; }
        public virtual Student Student { get; set; }
    }
}
